/**
 * 默认语言包
 */

export default {
	thirdpartyApplyBtn: "立即申请",
	serviceDepart: '服务部门',
	serviceOpenTiem: '起止时间',
	openingHoursText: '长期',
	taskSubmitBtn: '正式提交',
	xmlTab: '流程图',
	wxHotTit: '热门服务',
	rejectTips: '请立刻修改，重新提交',
	navPersonalEntry: '个人中心',
	mySubmit: "我的发起",
	myTask: "我的待办",
	noSubmit: "暂无数据",
	noTask: "暂无数据",
	noOversee: "暂无数据",
	noRead: "暂无数据",
	matterLog: '操作意见',
	thirdpartyBtnText: '查看表单',
	reportEmailExportText: "请输入邮箱地址",
	rejectText: "驳回",
	className: '服务分类',
	serviceHall: "服务大厅",
	serviceDepart: "服务部门",
	numberText: '学工号',
	infoQuery: "信息查询",
  m_startForm: "申请表单",
  loginSignUpText: '校外用户注册',
  loginpwdResetText: '校外用户忘记密码',
  loginSignUpPopText: '校外用户注册账户',
  sitePwdResetText: '校外用户密码找回',
	condsInstructions: '申请条件和说明',
	applicationDescription: '申请说明',
	postTheTracking:'公文办结',
	receiptOfTracking:'公文办结',
	detailZXPlace: "咨询地点",

}
