/**
 * 默认语言包
 */
export default {
  thirdpartyApplyBtn: '立即申请',
  serviceDepart: '服务部门',
  serviceOpenTiem: '起止时间',
  openingHoursText: '长期',
  taskSubmitBtn: '正式提交',
  xmlTab: '流程图',
  wxHotTit: '热门服务',
  rejectTips: '请立刻修改，重新提交',
  navPersonalEntry: '个人中心',
  mySubmit: '我的发起',
  myTask: '我的待办',
  noSubmit: '暂无数据',
  noTask: '暂无数据',
  noOversee: '暂无数据',
  noRead: '暂无数据',
  matterLog: '操作意见',
  thirdpartyBtnText: '查看表单',
  reportEmailExportText: '请输入邮箱地址',
  rejectText: '驳回',
  className: '服务分类',
  serviceHall: '服务大厅',
  serviceHallTwo: '服务大厅',
  numberText: '学工号',
  infoQuery: '信息查询',
  m_startForm: '申请表单',
  loginSignUpText: '校外用户注册',
  loginpwdResetText: '校外用户忘记密码',
  loginSignUpPopText: '校外用户注册账户',
  sitePwdResetText: '校外用户密码找回',
  recommendTabTit1: '学生办事',
  recommendTabTit2: '教师办事',
  recommendTabTit3: '访客办事',
  myTodoTit: '我的待办',
  formPrintText: '打印',
  processTracking: '流程跟踪',
  showTakeCloseText:'关闭页面',
  // 反馈
  feedbackContact: '联系方式',
  feedbackContactP: '默认系统手机号',
  feedbackHint: '',
  matterJumpType0: '需线下办理',
  matterJumpPc: '仅电脑端可发起',

  matterNameOrNum: '姓名/学工号',
  mFooterServiceText: '大厅',
  mFooterIndexText: '首页',

  launchToService: '去服务大厅看看',
  mFooterUserCenterText: '我的',

  // 预约
  reserveHallFacility: '硬件设施',

  rightNavFeedbackText: '我要反馈',
  reserveMsgHint: `预约时间段：{time} 预约咨询师：{consultant} 成功预约该咨询师次数：{count} 申请人：{user} 子资源名称：{name}`,
  matterTodoUploadName: '用户上传',
  reserveReasonText: '预约备注',

  userDataDepartTitle: '部门',
  siteIndexHotServeText: '热门服务',

  frontMenusMyHomePage: '我的主页',
  reverseHallPersonText: '人',
  reverseHallSuccess: '已成功预约',
  rightNavWeixinText: '关注微信公众号',
  myHomepageWork:'我要办事',
  backXHtext: '学号',
  backXGHtext: '学工号',
  matterReadScreenText: '知会的服务',
  noMatterReadDataText: '暂无知会任务',
  matterTodoReminder:'处理',
  matterTodoPending:'待处理',
  matterTodoBatch:'批量处理',
  matterTodoProcessed:'已处理'
}
